name: React App CI/CD with Minikube

on:
    workflow_dispatch: 

env:
  SONAR_HOST_URL: https://sonarcloud.io
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  ARTIFACT_NAME: react-app-build
  IMAGE_NAME: shiva1702/react-app
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-app-build
          path: build/



  sonar:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    needs: [build, sonar]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: react-app-build
          path: build/

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} \
          -t ${{ env.IMAGE_NAME }}:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Minikube and Kubectl
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/
          minikube start --driver=docker
          kubectl config use-context minikube

      - name: Enable Minikube Docker Env
        run: |
          eval $(minikube docker-env)
          docker pull ${{ env.IMAGE_NAME }}:${{ github.sha }}
          minikube image load ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl set image deployment/react-app react-app=${{ env.IMAGE_NAME }}:${{ github.sha }}
          kubectl rollout status deployment/react-app
