name: React App CI/CD with Minikube

on:
    workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build


#   sonar:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: SonarQube Scan
#         uses: SonarSource/sonarcloud-github-action@master
#         with:
#           projectBaseDir: .
#         env:
#           SONAR_TOKEN: ${{ secrets.bbcbcbf4780b3e6fb385aab3c7e6a4b30ddcb18b }}
#           SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
#           SONAR_PROJECT_KEY: ${{ env.SONAR_PROJECT_KEY }}

#   docker:
#     runs-on: ubuntu-latest
#     needs: [build, sonar]
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Download Artifact
#         uses: actions/download-artifact@v3
#         with:
#           name: ${{ env.ARTIFACT_NAME }}
#           path: build/

#       - name: Log in to DockerHub
#         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

#       - name: Build Docker Image
#         run: docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .

#       - name: Push Docker Image
#         run: docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}

#   deploy:
#     runs-on: ubuntu-latest
#     needs: docker
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Setup Minikube and Kubectl
#         run: |
#           curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
#           chmod +x minikube
#           sudo mv minikube /usr/local/bin/
#           minikube start --driver=docker
#           kubectl config use-context minikube

#       - name: Enable Minikube Docker Env
#         run: |
#           eval $(minikube docker-env)
#           docker pull ${{ env.IMAGE_NAME }}:${{ github.sha }}
#           minikube image load ${{ env.IMAGE_NAME }}:${{ github.sha }}

#       - name: Deploy to Minikube
#         run: |
#           kubectl apply -f k8s/deployment.yaml
#           kubectl set image deployment/react-app react-app=${{ env.IMAGE_NAME }}:${{ github.sha }}
#           kubectl rollout status deployment/react-app
